name: phone_state
description: This plugin allows you to know quickly and easily if your Android or iOS device is receiving a call and to know the status of the call.
version: 1.0.2
homepage: https://github.com/andreamainella98/phone_state

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: it.mainella.phone_state
        pluginClass: PhoneStatePlugin
      ios:
        pluginClass: PhoneStatePlugin